[package]
name = "shm"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
memmap2 = { workspace = true }
libc = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
